version: "3.9"

services:
  volume_init:
    image: busybox
    volumes:
      - quick_sf_volume:/var/lib/postgresql/data
      - ./podman-postgres:/backup:ro
    networks:
      - quick_sf_net
    command: sh -c "tar -xvf /backup/sofime_scenario_001.tar -C /var/lib/postgresql/data && chown -R 777 /var/lib/postgresql/data && touch /var/lib/postgresql/data/.initialized"
    restart: "no"
  postgres:
    build:
      context: ./podman-postgres
      args:
        EXPOSED_PORT: "17"
        APP_JAR: "myapp.jar"
    container_name: quick-sf-pg
    hostname : quick-sf-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: not24get
      POSTGRES_DB: oa_prod
    volumes:
      - type: volume
        source: quick_sf_volume
        target: /var/lib/postgresql/data
    networks:
      - quick_sf_net
    ports:
      - "5433:5432"
    entrypoint: sh -c "while [ ! -f /var/lib/postgresql/data/.initialized ]; do sleep 10; done && docker-entrypoint.sh postgres"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 25
  openage:
    build:
      context: ./podman-tomcat
      args:
        EXPOSED_PORT: "9170"
        CONTAINER_NAME_DB: "quick-sf-pg"
        WAR_NAME: "openage"
    container_name: quick-sf-oa
    hostname : quick-sf-oa
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: oa_prod
      DB_USER: postgres
      DB_PASSWORD: not24get
      EXPOSED_PORT: 8787
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - quick_sf_net
    ports:
      - "8686:8080"
  viewer:
    build:
      context: ./podman-vs
      args:
        EXPOSED_PORT: "9170"
        CONTAINER_NAME_DB: "quick-sf-pg"
    container_name: quick-sf-vs
    user: "1042:1042"
    environment:
      JAVA_OPTS: "-Dosgi.ee.default=JavaSE-1.8-compact2"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: oa_prod
      DB_USER: postgres
      DB_PASSWORD: not24get
      NGINX_PORT: 8686
    volumes:
      - ./podman-vs/conf:/home/vsh/conf:U
      - ./podman-vs/plugins:/home/vsh/plugins:U
      - ./podman-vs/assets:/home/vsh/assets:U
      - ./podman-vs/logs:/home/vsh/logs:U
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - quick_sf_net
    ports:
      - "9170:9170"
  nginx:
    image: docker.io/nginx:latest
    container_name: nginx
    ports:
      - "8787:80"    # HTTP
    volumes:
      - ./podman-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./podman-nginx/conf.d:/etc/nginx/conf.d:ro
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - quick_sf_net
volumes:
  quick_sf_volume:

networks:
  quick_sf_net:
    driver: bridge
