server {
	client_max_body_size 8M;
	listen 80 default_server;
	listen [::]:80 default_server;

	#root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name _;


	location /openage/ {
		#add_header 'Access-Control-Allow-Origin' '*'
                proxy_pass    http://quick-sf-oa:8080/openage/;
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                #try_files $uri $uri/ =404;
                proxy_set_header Upgrade $http_upgrade;
    		proxy_set_header Connection "Upgrade";
    		proxy_set_header Host $host;
        }
        
        location /relocation/ {
	 	proxy_pass    http://quick-sf-vs:9170/relocation/;
	 	proxy_set_header Upgrade $http_upgrade;
    		proxy_set_header Connection "Upgrade";
    		proxy_set_header Host $host;
    		proxy_cookie_path /qare /;
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		#try_files $uri $uri/ =404;
	}
}

